sudo: required
services:
  - docker

before_install:
  - docker build -t mattcleary/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test
  
after_success:
  - docker build -t mattcleary/multi-client ./client
  - docker build -t mattcleary/multi-nginx ./nginx
  - docker build -t mattcleary/multi-server ./server
  - docker build -t mattcleary/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mattcleary/multi-client
  - docker push mattcleary/multi-nginx
  - docker push mattcleary/multi-server
  - docker push mattcleary/multi-worker

  