sudo: required
services:
  - docker

before_install:
  - docker build -t judgejab/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run judgejab/react-test npm test -- --coverage

after_success:
  - docker build -t judgejab/multi-client ./client
  - docker build -t judgejab/multi-nginx ./nginx
  - docker build -t judgejab/multi-server ./server
  - docker build -t judgejab/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push judgejab/multi-client
  - docker push judgejab/multi-nginx
  - docker push judgejab/multi-server
  - docker push judgejab/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: arn:aws:s3:::elasticbeanstalk-us-east-1-190947864732
  bucket_path: docker_multi
  on: 
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY




  